Finished second milestone
MkrtichSargsyan/ror-social-scaffold pull request #2
Opened 2020-12-18 21:03 UTC by MkrtichSargsyan

In this milestone, I created different users who can send invitations , show their friends list, and also reject invitations

2020-12-18 22:38 UTC, lekegitrepo requested changes
## Status: Changes Required! :recycle:
### Hi @MkrtichSargsyan :clap: :clap:
#### You have done a good job :+1: The associations between active records are well implemented. However, some requirements are missing/not implemented correctly. Check my comments below :point_down:

#### App Behaviour:
- _User should be able to see friendship requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Currently, the user does not know if they have a request(nothing indicate if a user has friend request)._
- _User has to accept a friendship request to start a friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). There is no button to accept a friend request._

- _User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). There is no button to reject a friend request._
- _There is a button to invite a user to friendship on the users' list page and on the single-user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). The button appears when I start the app and the moment I sent a first friend request, the button did not appear again both in the users' list page and in the single-user page._
- _Posts timeline should include posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). The posts are visible to any logged-in user right now either the author of the post is a friend of the current user or not._

#### Tests:
- Add more tests that cover the remaining models, controller, and(if possible you can add) integration tests to cover the typical user interaction with the application such as sign in, sign up, friend request, reject the request and accept the request.

#### Logic in the view:
- _There should be NO application logic in the views. Everything connected with data processing should be encapsulated in models and used in controllers._
- _View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)_
- _There should be absolutely NO logic in views. >Views are only for displaying information that became available to it from its corresponding controller not generating it. **Check these resources**_
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

#### _Reviewed by Temitayo Adeleke_

2020-12-18 22:38 UTC, lekegitrepo commented on app/views/users/_friends_table.html.erb
> +        <%= "<b>No friends yet</b>".html_safe if @user.friends.empty? %>
- **_There should be NO logic in the view_**

2020-12-18 22:38 UTC, lekegitrepo commented on app/views/users/_friends_table.html.erb
> +          <% if @user == current_user %>
- **_There should be NO logic in the view_**

2020-12-18 22:38 UTC, lekegitrepo commented on app/views/users/_friends_table.html.erb
> +        <%= "<b>No friend requests</b>".html_safe if @user.friend_requests.empty? %>
- **_There should be NO logic in the view_**

2020-12-18 22:38 UTC, lekegitrepo commented on app/views/users/_user.html.erb
> +    <% end %>
- **_There should be NO logic in the view_**

2020-12-18 22:38 UTC, lekegitrepo commented on app/views/users/show.html.erb
> +    <%= "<b>Already friend</b>".html_safe if @user.friends.include?(current_user) %>
- **_There should be NO logic in the view_**

2020-12-19 02:49 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### Great job on your progress so far 👍 

Looks like you left out a couple of changes requested by the previous TSE, please, lets kindly address those:

- [ ] There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it.  
See affected files below:
> * `layouts/_navigation.html.erb`
> * `layouts/application.html.erb`
> * `users/_friends_table.html.erb`
> * `users/_user.html.erb`
> * `users/show.html.erb`

**The Resources below may come in handy**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [Rails View Helpers Best Practices](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

- [ ] Add more tests coverage, you currently have tested just for the user model, kindly add for the remaining models, controller,  also include integration tests.
- [ ] It will be nice to also have the **Accept or Reject** request button on the users list page and on the single-user page

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-12-19 02:49 UTC, acushlakoncept commented on app/views/layouts/_navigation.html.erb
> +    <% end %>
There should be NO logic in the view

2020-12-19 02:49 UTC, acushlakoncept commented on app/views/layouts/application.html.erb
> -      <% end %>
There should be NO logic in the view

2020-12-19 02:49 UTC, acushlakoncept commented on app/views/users/_friends_table.html.erb
> +        <%= "<b>No friends yet</b>".html_safe if @user.friends.empty? %>
There should be NO logic in the view

2020-12-19 02:49 UTC, acushlakoncept commented on app/views/users/_user.html.erb
> +    <% end %>
There should be NO logic in the view

2020-12-19 02:49 UTC, acushlakoncept commented on app/views/users/show.html.erb
> +    <%= "<b>Already friend</b>".html_safe if @user.friends.include?(current_user) %>
There should be NO logic in the view

2020-12-20 16:24 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### Great job! 👏  Both of you have done well on this project.

However, there are still some changes that are necessary for this project to be approved.
Let us quickly add some finishing touches and request another review.

- [ ] It will be nice to also have the Accept or Reject request button on the users' list page and on the single-user page
![acc](https://user-images.githubusercontent.com/5264771/102718293-a9e27000-42e7-11eb-8e4c-0e1c3dc99d52.jpg)

- [ ] I noticed you still have logic in your views, see the comments below and address them accordingly.

Having trouble? **The Resources below may come in handy**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [Rails View Helpers Best Practices](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-12-20 16:24 UTC, acushlakoncept commented on app/views/users/show.html.erb
> +    <%= "<b>Already friend</b>".html_safe if @user.friends.include?(current_user) %>
- [ ] There should be NO application logic in the views nor helpers (no Post.new, Comment.create, current_user.friends.find_by(...)...). Everything connected with data processing should be encapsulated in models and used in controllers.

2020-12-20 16:24 UTC, acushlakoncept commented on app/views/layouts/application.html.erb
>        <div class="notice">
There should be NO logic in the view

2020-12-20 19:18 UTC, Spayco approved these changes
# Project Approved

thank you for making the required changes, your project is now approved!

**_please be more professional with your commit messages, I understand having many TSEs asking for changes can be frustrating, but we shouldn't let frustration control our actions_**

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-12-20 19:21 UTC, merged